name: Dockerized App Deployment
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 24700
          script: |
            cd /root/instagraaa/instagram-clone-fe
            git fetch origin 
            git checkout master
            git pull origin master
            docker build -t instagram-clone-fe .
            docker stop instagram-clone-fe-container || true
            docker rm instagram-clone-fe-container || true
            docker run -d --name instagram-clone-fe-container -p 4003:3000 instagram-clone-fe
            docker ps -a
            docker images
